version: '3'

services:

  game-api:
    build:
      context: ./../game-api
      dockerfile: ./../game-api/game-api.dockerfile
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1
  
  # rabbitmq:
  #   image: 'rabbitmq:3.9-alpine'
  #   ports:
  #     - "5672:5672"
  #   deploy:
  #     mode: replicated
  #     replicas: 1
  #   volumes:
  #     - ./db-data/rabbitmq/:/var/lib/rabbitmq/

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - ./db-data/redis/:/data/redis

